language: php

dist: trusty

sudo: required

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

env:
  - ILLUMINATE_VERSION=5.5.*

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true
  include:
    - php: 7.1
      env: ILLUMINATE_VERSION=5.6.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.7.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.8.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.6.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.7.*
    - php: 7.2
      env: ILLUMINATE_VERSION=5.8.*
    - php: 7.3
      env: ILLUMINATE_VERSION=5.6.*
    - php: 7.3
      env: ILLUMINATE_VERSION=5.7.*
    - php: 7.3
      env: ILLUMINATE_VERSION=5.8.*
    - php: nightly
      env: ILLUMINATE_VERSION=5.6.*
    - php: nightly
      env: ILLUMINATE_VERSION=5.7.*
    - php: nightly
      env: ILLUMINATE_VERSION=5.8.*

before_install:
  - ssh-keygen -t rsa -f ~/.ssh/id_rsa -q -P ""
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - chmod 0600 ~/.ssh/{authorized_keys,id_rsa,id_rsa.pub}
  - eval "$(ssh-agent -s)" #start the ssh agent
  - ssh-add
  - composer self-update
  - composer require "illuminate/console:${ILLUMINATE_VERSION}" --no-update
  - composer require "illuminate/support:${ILLUMINATE_VERSION}" --no-update

install:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest

script:
  - vendor/bin/phpunit
